backend/kds_stroy/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from kds_stroy import settings
from main.views import MainView, handler404
from users.views import RegistrationView

urlpatterns = [
    path("", MainView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("auth/registration/", RegistrationView.as_view(), name="registration"),
    path("auth/", include("django.contrib.auth.urls")),
    path("locations/", include("locations.urls")),
    path("news/", include("news.urls")),
    path("orders/", include("orders.urls")),
    path("profile/", include("users.urls")),
    path("subs/", include("ads_mailing.urls")),
    path("terms/", TemplateView.as_view(template_name="pages/personal_terms.html"), name="personal_info_terms"),
    path("verification/", include("verify_email.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

handler404 = handler404

backend/news/urls.py
from django.urls import path

from news.views import NewsListView, NewsDetailView

app_name = "news"

urlpatterns = [
    path("", NewsListView.as_view(), name="list"),
    path("<int:pk>/", NewsDetailView.as_view(), name="detail"),
]

backend/main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from ads_mailing.forms import SubscribeForm


def handler404(request, exception):
    return render(request, "404.html", status=404)


class MainView(TemplateView):
    template_name = "pages/main.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["subscribe_form"] = SubscribeForm()
        return context

backend/templates/pages/news_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}КДС-Строй: Новости{% endblock title %}
{% block plug_js_css %}
  <script type="module" crossorigin src="{% static 'js/pages/news-detail-page.js' %}"></script>
  <link rel="stylesheet" crossorigin href="{% static 'css/singleNews-dKyUe2RX.css' %}">
{% endblock plug_js_css %}

{% block content %}
<main>
  <section class="single-news">
    <div class="container single-news__container">
      <a class="single-news__link single-news__link--top" href="{% url "news:list" %}">
        <span>Все новости</span>
      </a>
      <h1 class="single-news__title">{{ news.title }}</h1>
      <div class="single-news__row">
        <div class="single-news__slider swiper" id="photo-container">
          <div class="single-news__date">{{ news.published_date }}</div>
          <div class="single-news__slider-wrapper swiper-wrapper">
            {% for photo in news.photos.all %}
              <div class="single-news__slide swiper-slide">
                <a class="single-news__slide-image-wrapper" href="{{ photo.photo.url }}" data-fancybox="news-0">
                  <img src="{{ photo.photo.url }}" alt="Изображение новости">
                </a>
              </div>
            {% endfor %}
          </div>
          <div class="swiper-pagination single-news__slider-pagination"></div>
        </div>
        <div class="single-news__text-wrapper">
          <div class="single-news__text">{{ news.content|safe }}</div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock content %}

backend/templates/pages/news_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}КДС-Строй: Новости{% endblock title %}
{% block plug_js_css %}
  <script type="module" crossorigin src="{% static 'js/pages/news-list-page.js' %}"></script>
  <link rel="stylesheet" crossorigin href="{% static 'css/news-Iqa5z6dR.css' %}">
{% endblock plug_js_css %}
{% block content %}

<main>
    <section class="news">
        <div class="container news__container">
            <h1 class="news__title">Новости</h1>
            <div class="news__controls">
                <button class="news__controls-date" type="button" id="news-sort-date">Дата</button>
                <div class="news__controls-themes select">
                    <input class="select__input" type="hidden" name="number">
                    <button class="select__current">Все новости</button>
                    <div class="select__list">
                        <button class="select__item" data-value="all">Все новости</button>
                    {% if categories.count != 0 %}
                      {% for category in categories %}
                        <button class="select__item" data-value="{{ category.slug }}">{{ category.title }}</button>
                      {% endfor %}
                    {% endif %}
                    </div>
                </div>
            </div>
            <ul class="news__list">
                {% for news in page_obj %}
                  <li class="news__list-item">
                    <div class="news__list-item-image-wrapper">
                      <a href="{% url 'news:detail' news.id %}">
                        <img src="{{ news.photos.first.photo.url }}" alt="Изображение новости">
                      </a>
                    </div>
                    <div class="news__list-item-content-wrapper">
                        <p class="news__list-item-date">{{ news.published_date }}</p>
                        <a class="news__list-item-link" href="{% url 'news:detail' news.id %}">
                            <h2 class="news__list-item-title">{{ news.title }}</h2>
                        </a>
                        <div class="news__list-item-text">{{ news.content|truncatechars:400|safe}}</div>
                        <a href="{% url 'news:detail' news.id %}">Читать&nbsp;полностью</a>
                    </div>
                  </li>
                {% endfor %}
            </ul>
            {% if page_obj.has_other_pages %}
              <div class="news__pagination">
                {% if page_obj.has_previous %}
                  <a class="news__pagination__item" href="?page=1">&laquo;</a>
                  <a class="news__pagination__item" href="?page={{ page_obj.previous_page_number }}">&lt;</a>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                    <a class="news__pagination__item{% if page_obj.number == i %} news__pagination__item--active{% endif %}" href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
                {% if page_obj.has_next %}
                  <a class="news__pagination__item" href="?page={{ page_obj.next_page_number }}">&gt;</a>
                  <a class="news__pagination__item" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                {% endif %}
              </div>
            {% endif %}
        </div>
    </section>
</main>
{% endblock content %}